os:
  - linux
  - osx

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never

 # Setup anaconda
before_install:
  # setup conda (for Python 2 or 3)
  - chmod +x setup_conda.py
  - ./setup_conda.py setup ./conda
  # fix for multiprocessing bug
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_TAG
  - export PATH=/home/travis/miniconda/bin:$PATH
  - ./setup_conda.py build ./conda

env:
  global:
    secure: uwdgq+mWwgROLeY51aqJrGJcd/dOLWYqsURkqsCUQhWeg9s5mQ0q0G+WZgmoVrY9htn5ORdq9r45ZnZiSPTYmjbw28iB4w1iOzcUZYjQg18AZ3QSZzbkNkVRbOWJZ//3g/T2he1dIa0euk5Mk9qx06+r2OfAgpvOaG8XwB/idRU=
  matrix:
    - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
    - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh
