os:
- linux
- osx

env:
  global:
  - secure: GQYQKvT5N+ZP45jP/DqvBdSy3QLnkchGlV55qxghpqAlz5cqR6RMBSH8IIVF1UDqzbQQ1C8P4ziWX5OQ179Cu0qbXUCxUeG/bmY9FemR9F+OfVed5cPCEA6/AtqCCQfOPTDUoVB8syJTrUNjPelB3CT6astwAZH+OeJl3vOQfcU=
  matrix:
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh

install:
- wget https://raw.githubusercontent.com/jabooth/traviconda/beta/traviconda.py -O traviconda.py
- chmod +x traviconda.py
- ./traviconda.py setup --url $MINICONDA_URL --channel menpo
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- ./traviconda.py build ./conda --user menpo --key $BINSTAR_KEY

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
