os:
- linux
- osx

env:
  global:
  - secure: GQYQKvT5N+ZP45jP/DqvBdSy3QLnkchGlV55qxghpqAlz5cqR6RMBSH8IIVF1UDqzbQQ1C8P4ziWX5OQ179Cu0qbXUCxUeG/bmY9FemR9F+OfVed5cPCEA6/AtqCCQfOPTDUoVB8syJTrUNjPelB3CT6astwAZH+OeJl3vOQfcU=
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

install:
- wget https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py -O traviconda.py
- python traviconda.py setup $PYTHON_VERSION --channel menpo
- export CYASSIMP_VERSION=$(python traviconda.py version)
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- python traviconda.py auto ./conda --binstaruser menpo --binstarkey $BINSTAR_KEY --pypiuser $PYPI_USERNAME  --pypipassword $PYPI_PASSWORD

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
