package:
  name: cyassimp
#  version: {% if environ.get('GIT_DESCRIBE_NUMBER', 0) == 0 %} {{ environ['GIT_DESCRIBE_TAG'] }} {% else %} {{ environ.get('GIT_BUILD_STR', '') }} {% endif %}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}
  #version: 0.1.4_28_gf23dd5c

requirements:
  build:
    - python
    - distribute
    - numpy
    - cython
    - assimp

  run:
    - python
    - numpy
    - assimp [unix]
	
test:
  imports:
    - cyassimp

about:
  home: https://github.com/menpo/cyassimp/
  license: BSD License
