package:
  name: cyassimp
  version: {{ environ['PACKAGE_VERSION'] }}

requirements:
  build:
    - python
    - distribute
    - numpy
    - cython
    - assimp

  run:
    - python
    - numpy
    - assimp [unix]
	
test:
  imports:
    - cyassimp

about:
  home: https://github.com/menpo/cyassimp/
  license: BSD License
