package:
  name: cyassimp
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - cython >=0.21.0
    - assimp 3.0.1270

  run:
    - python
    - numpy >=1.10
    - assimp 3.0.1270  # [unix]

test:
  imports:
    - cyassimp

about:
  home: https://github.com/menpo/cyassimp/
  license: BSD License
